sequenceDiagram
    participant browser
    participant server

    Note right of browser: O usuário clica no botão 'Save' e o formulário é enviado

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    activate server
    server-->>browser: HTTP status code 302 (URL redirect)
    deactivate server

    Note right of browser: O servidor pede para o navegador fazer uma nova requisição HTTP GET para o endereço das notas

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server-->>browser: HTML document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: the css file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: the JavaScript file
    deactivate server

    Note right of browser: O navegador começa a executar o código JavaScript que busca o JSON do servidor

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: [{ "content": "Nova nota", "date": "2025-..." }, ... ]
    deactivate server

    Note right of browser: O navegador executa a função callback que renderiza as notas atualizadas