sequenceDiagram
    participant browser
    participant server

    Note right of browser: --- FASE 1: CARREGAMENTO DA SPA ---

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa
    activate server
    server-->>browser: HTML document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: main.css
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
    activate server
    server-->>browser: spa.js
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: [{ "content": "SPA carrega tudo antes", "date": "..." }]
    deactivate server

    Note right of browser: --- FASE 2: USUÁRIO ENVIA O FORMULÁRIO ---<br/>O usuário escreve e clica em Salvar. <br/>O JS previne o reload e envia apenas o JSON.

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    server-->>browser: {"message": "note created"} (201 Created)
    deactivate server

    Note right of browser: O navegador permanece na mesma página.<br/>A lista é atualizada via JavaScript localmente.